package com.example.demo.dao;

import com.example.demo.dao.FooBar;
import com.example.demo.dao.FooBarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FooBarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    long countByExample(FooBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int deleteByExample(FooBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int insert(FooBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int insertSelective(FooBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    List<FooBar> selectByExampleWithRowbounds(FooBarExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    List<FooBar> selectByExample(FooBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    FooBar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FooBar record, @Param("example") FooBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FooBar record, @Param("example") FooBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FooBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foo_bar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FooBar record);
}